//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEIMA.Backend {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BEIMA.Backend.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building could not be found..
        /// </summary>
        internal static string BuildingNotFoundMessage {
            get {
                return ResourceManager.GetString("BuildingNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building is null..
        /// </summary>
        internal static string BuildingNullMessage {
            get {
                return ResourceManager.GetString("BuildingNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The building could not be deleted because at least one device exists in the database with this building..
        /// </summary>
        internal static string CannotDeleteBuildingMessage {
            get {
                return ResourceManager.GetString("CannotDeleteBuildingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device type could not be deleted because at least one device exists in the database with this device type..
        /// </summary>
        internal static string CannotDeleteDeviceTypeMessage {
            get {
                return ResourceManager.GetString("CannotDeleteDeviceTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse the request body..
        /// </summary>
        internal static string CouldNotParseBody {
            get {
                return ResourceManager.GetString("CouldNotParseBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device could not be found..
        /// </summary>
        internal static string DeviceNotFoundMessage {
            get {
                return ResourceManager.GetString("DeviceNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is null..
        /// </summary>
        internal static string DeviceNullMessage {
            get {
                return ResourceManager.GetString("DeviceNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device type could not be found..
        /// </summary>
        internal static string DeviceTypeNotFoundMessage {
            get {
                return ResourceManager.GetString("DeviceTypeNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device year manufactured is invalid..
        /// </summary>
        internal static string DeviceYearManufacturedInvalidMessage {
            get {
                return ResourceManager.GetString("DeviceYearManufacturedInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal server error has occurred..
        /// </summary>
        internal static string InternalServerErrorMessage {
            get {
                return ResourceManager.GetString("InternalServerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id..
        /// </summary>
        internal static string InvalidIdMessage {
            get {
                return ResourceManager.GetString("InvalidIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is invalid..
        /// </summary>
        internal static string InvalidLocationMessage {
            get {
                return ResourceManager.GetString("InvalidLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The max character length on field &quot;{0}&quot; has been exceeded..
        /// </summary>
        internal static string MaxCharacterLengthExceededMessage {
            get {
                return ResourceManager.GetString("MaxCharacterLengthExceededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User could not be found..
        /// </summary>
        internal static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
    }
}
